import ProfilePicture from 'public/profile-picture.png';

const mockedExperiences = [
  {
    id: 'aosp-1',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-2',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-3',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-4',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-5',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-6',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-7',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-8',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-9',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-10',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-11',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-12',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-13',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-14',
    displayName: 'AOSP With A Very Long Name That Will Break The Layout',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-15',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-16',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
  {
    id: 'aosp-17',
    displayName: 'AOSP',
    isActive: false,
    description: 'Android Open Source Project',
    role: 'Android Developer',
    imageUrls: [ProfilePicture],
    gitUrl: 'https://android.googlesource.com/',
    webUrl: 'https://source.android.com/',
    startedAt: new Date('2019-01-01'),
    technologies: ['react', 'sass', 'typescript'],
  },
];

export const experienceAction = {
  async all() {
    return new Promise<typeof mockedExperiences>(resolve =>
      setTimeout(() => resolve(mockedExperiences), 1000),
    );
  },
  async get(id: string) {
    return new Promise<(typeof mockedExperiences)[number]>((resolve, reject) =>
      setTimeout(() => {
        const experience = mockedExperiences.find(experience => experience.id === id);
        if (experience) {
          resolve(experience);
        } else {
          reject(new Error('Experience not found'));
        }
      }, 1000),
    );
  },
};
